spring:
  data:
    redis:
      port: 6379
      password: 123456
      host: 127.0.0.1
  mail:
    username: dinglei@163.com #登陆账号
    password: dinglei #登陆密码（或授权码）
    properties:
      from: dinglei@163.com #邮件发信人（即真实邮箱）
blog:
  aliyun:
    access-key-id: accessKeyId
    access-key-secret: accessKeySecret
  jwt:
    secret: ti8n3439n439t43ld9nv9343ddfer09hti8n3439n439t43ld9nv9343ddfer09ti8n3439n439t43ld9nv9343ddfer09fti8n3439n439t43ld9nv9343ddfer09f
