package wiki.chiu.micro.cache.handler;

import java.util.Set;

/** Deletes exact L2 keys and broadcasts L1 invalidation to every cache replica. */
public interface CacheEvictor {

  /**
   * Evicts all supplied keys while holding their distributed load locks.
   *
   * @param keys exact keys generated by {@code CacheKeyFactory}
   * @throws RuntimeException when locking, deletion, or confirmed broadcast fails
   */
  void evict(Set<String> keys);
}
