local redis_time = redis.call('TIME')
local now_ms = tonumber(redis_time[1]) * 1000 + math.floor(tonumber(redis_time[2]) / 1000)
local expires_at = now_ms + tonumber(ARGV[1])
redis.call('ZADD', KEYS[1], expires_at, ARGV[2])
redis.call('HSET', KEYS[2], ARGV[2], ARGV[3])
redis.call('ZADD', KEYS[3], expires_at, ARGV[2])
redis.call('PEXPIRE', KEYS[3], ARGV[4])
redis.call('PEXPIRE', KEYS[4], ARGV[4])
redis.call('PEXPIRE', KEYS[5], ARGV[4])
redis.call('PEXPIRE', KEYS[6], ARGV[4])
redis.call('PEXPIRE', KEYS[7], ARGV[4])
redis.call('PEXPIRE', KEYS[8], ARGV[4])
redis.call('PEXPIRE', KEYS[9], ARGV[4])
redis.call('PEXPIRE', KEYS[10], ARGV[4])
return 1
