name: GraalVM build Gateway
on:
  push:
    branches:
      - 'main'
    paths:
      - 'micro-gateway/**'
      - 'build.gradle.kts'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
      - name: Prepare
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Info
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build
        run: ./gradlew :micro-gateway:bootBuildImage
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PWD: ${{ secrets.DOCKERHUB_PWD }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull mingchiuli/megalith-micro-gateway:latest
            docker stop $(docker ps | grep 'micro-gateway' | awk '{print $1}')
            docker rm $(docker ps -a | grep 'micro-gateway' | awk '{print $1}')
            docker compose --compatibility up -d --no-recreate
            docker rmi $(docker images | grep 'micro-gateway' | grep 'none' | awk '{print $3}')
            code=$(docker images | grep 'micro-gateway' | grep 'none' | awk '{print $3}')
            if [ -n "$code" ]; then
              docker rmi $code
            fi